# set(OBJCOPY_BIN_PATH ${ARM_NONE_EABI_PREFIX}-objcopy${TOOLCHAIN_EXT})
find_program(OBJCOPY_BIN ${ARM_NONE_EABI_PREFIX}-objcopy${TOOLCHAIN_EXT} REQUIRED)

# set(ARM_SIZE_PATH ${ARM_NONE_EABI_PREFIX}-size${TOOLCHAIN_EXT})
find_program(ARM_SIZE ${ARM_NONE_EABI_PREFIX}-objcopy${TOOLCHAIN_EXT} REQUIRED)